workspace = { }

[package]
name = "GatsbyThemedSiteApp"
version = "0.1.0"
description = "Gatsby themed site built by Tauri"
author = [ "you" ]
license = ""
repository = ""
default-run = "GatsbyThemedSiteApp"
edition = "2018"

[package.metadata.bundle]
identifier = "com.tauri.dev"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]

[dependencies]
serde_json = "1.0.44"
serde = "1.0"
serde_derive = "1.0"
tiny_http = "0.6"
phf = "0.8.0"
includedir = "0.5.0"

  [dependencies.tauri]
  version = "^0.2"
  features = [ "edge" ]

[features]
dev = [ "tauri/dev" ]
embedded-server = [ "tauri/embedded-server" ]

[[bin]]
name = "GatsbyThemedSiteApp"
path = "src/main.rs"
