[workspace]
members = [
  "core",
  "src-tauri"
]

[workspace.package]
version = "1.0.0"

[workspace.dependencies]
tauri-build = { path = "../../core/tauri-build", features = [] }
tauri = { path = "../../core/tauri", features = [] }
