# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

version: 2
updates:
  # NPM packages
  - package-ecosystem: 'npm'
    directory: '/tooling/api'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'npm'
    directory: '/tooling/cli/node'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0

  # Tooling
  - package-ecosystem: 'cargo'
    directory: '/tooling/cli'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/tooling/bundler'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/tooling/webdriver'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0

  # Core
  - package-ecosystem: 'cargo'
    directory: '/core/tauri'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-build'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-codegen'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-macros'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-runtime'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-runtime-wry'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-utils'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
    # disable version updates
    open-pull-requests-limit: 0
