[package]
name = "tauri_app"
version = "0.1.0"
description = "A very simple Dll Library that runs tauri and launches a webview window"
edition = "2021"
rust-version = "1.70"

[workspace]

[lib]
crate-type = ["cdylib"]

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = [ "codegen" ] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { path = "../../../core/tauri", features = [] }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
