[package]
name = "multiwindow"
version = "0.1.0"
description = "An example Tauri Multi-Window Application"
edition = "2018"
license = "Apache-2.0/MIT"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build" }

[dependencies]
tauri = { path = "../../../core/tauri", features =["api-all"]}

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
