[package]
name = "<%= name %>"
version = "1.0.0"
categories = ["wasm"]
edition = "2021"
rust-version = "1.57"
description = ""

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[workspace]
members = [
  "src-tauri"
]

[dependencies]
console_error_panic_hook = "0.1.6"
dominator = "0.5.17"
wasm-bindgen = "0.2.74"
futures-signals = "0.3.20"
once_cell = "1.7.2"
