[package]
name = "tauri-build"
version = "1.0.0-beta.3"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri/tree/dev/core/tauri-build"
description = "build time code to pair with https://crates.io/crates/tauri"
edition = "2018"
exclude = [ ".license_template", "CHANGELOG.md", "/target" ]
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]

[dependencies]
anyhow = "1"
proc-macro2 = "1"
quote = "1"
tauri-codegen = { version = "1.0.0-beta.3", path = "../tauri-codegen", optional = true }

[target."cfg(windows)".dependencies]
winres = "0.1"
serde_json = "1.0"
tauri-utils = { version = "1.0.0-beta.0", path = "../tauri-utils", features = [ "build" ] }

[features]
codegen = [ "tauri-codegen" ]
