[package]
name = "tauri-build"
version = "1.0.0-beta-rc.0"
authors = [ "Tauri Community" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri/tree/dev/core/tauri-build"
description = "build time code to pair with https://crates.io/crates/tauri"
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]

[dependencies]
anyhow = "1"
proc-macro2 = "1"
quote = "1"
tauri-codegen = { path = "../tauri-codegen", optional = true }

[target."cfg(windows)".dependencies]
winres = "0.1"

[features]
codegen = [ "tauri-codegen" ]
