[package]
name = "updater-example"
version = "0.1.0"
description = "A very simple Tauri Application"
edition = "2021"
rust-version = "1.57"
license = "Apache-2.0 OR MIT"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["codegen"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { path = "../../../core/tauri", features = ["updater"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[[bin]]
name = "updater-example"
path = "src/main.rs"

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
