[package]
name = "app"
version = { workspace = true }
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.65"

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { workspace = true }
core-api = { path = "../core" }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
