[package]
name = "isolation"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { path = "../../core/tauri-build", features = ["isolation"] }

[dependencies]
tauri = { path = "../../core/tauri", features = ["isolation"] }
