[package]
name = "resources"
version = "0.1.0"
description = "A Tauri application that uses Node.js with app resources"
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["codegen"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { path = "../../../core/tauri" }
