[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.70"
license = "Apache-2.0 OR MIT"

[lib]
name = "api_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["codegen", "isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tiny_http = "0.11"
log = "0.4"
tauri-plugin-sample = { path = "./tauri-plugin-sample/" }

[target."cfg(any(target_os = \"macos\", windows, target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
tauri-plugin-cli = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "next" }

[patch.crates-io]
tauri = { path = "../../../core/tauri" }
tauri-build = { path = "../../../core/tauri-build" }

[patch.'https://github.com/tauri-apps/tauri']
tauri = { path = "../../../core/tauri" }
tauri-build = { path = "../../../core/tauri-build" }

[dependencies.tauri]
path = "../../../core/tauri"
features = [
  "protocol-asset",
  "icon-ico",
  "icon-png",
  "isolation",
  "macos-private-api",
  "tray-icon"
]

[dev-dependencies.tauri]
path = "../../../core/tauri"
features = ["test"]

[target."cfg(target_os = \"windows\")".dependencies]
window-shadows= "0.2"

[features]
custom-protocol = [ "tauri/custom-protocol" ]

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
