[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.63"
license = "Apache-2.0 OR MIT"

[lib]
name = "api_lib"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["codegen", "isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tiny_http = "0.11"

[dependencies.tauri]
path = "../../../core/tauri"
features = [
  "api-all",
  "cli",
  "global-shortcut",
  "http-multipart",
  "icon-ico",
  "icon-png",
  "isolation",
  "macos-private-api",
  "windows7-compat",
  "system-tray",
  "updater"
]

[dev-dependencies.tauri]
path = "../../../core/tauri"
features = ["test"]

[target."cfg(target_os = \"windows\")".dependencies]
window-shadows= "0.2"

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
log = "0.4"
tauri-runtime-wry = { path = "../../../core/tauri-runtime-wry/" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.9.0"
jni = "0.19.0"
paste = "1.0"

[target.'cfg(target_os = "ios")'.dependencies]
mobile-entry-point = "0.1.0"
env_logger = "0.9.0"

[features]
custom-protocol = [ "tauri/custom-protocol" ]

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
