[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.70"
license = "Apache-2.0 OR MIT"

[lib]
name = "api_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["codegen", "isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tiny_http = "0.11"
log = "0.4"
tauri-plugin-sample = { path = "./tauri-plugin-sample/" }

[dependencies.tauri]
path = "../../../core/tauri"
features = [
  "protocol-asset",
  "image-ico",
  "image-png",
  "isolation",
  "macos-private-api",
  "tray-icon",
]

[dev-dependencies.tauri]
path = "../../../core/tauri"
features = ["test"]

[features]
prod = ["tauri/custom-protocol"]
