[package]
name = "tauri-codegen"
version = "1.0.0-rc.3"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri/tree/dev/core/tauri-codegen"
description = "code generation meant to be consumed inside of `tauri` through `tauri-build` or `tauri-macros`"
edition = "2021"
rust-version = "1.57"
exclude = [ ".license_template", "CHANGELOG.md", "/target" ]
readme = "README.md"

[dependencies]
sha2 = "0.10"
base64 = "0.13"
blake3 = { version = "1.3", features = [ "rayon" ] }
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tauri-utils = { version = "1.0.0-rc.3", path = "../tauri-utils", features = [ "build" ] }
thiserror = "1"
walkdir = "2"
zstd = { version = "0.10", optional = true }
regex = { version = "1", optional = true }
uuid = { version = "0.8", features = [ "v4" ] }

[target."cfg(windows)".dependencies]
ico = "0.1"

[target."cfg(target_os = \"linux\")".dependencies]
png = "0.17"

[features]
default = [ "compression" ]
compression = [ "zstd", "tauri-utils/compression" ]
isolation = [ "tauri-utils/isolation" ]
__isolation-docs = [ "tauri-utils/__isolation-docs" ]
shell-scope = [ "regex" ]
config-json5 = [ "tauri-utils/config-json5" ]
