[package]
name = "tauri-codegen"
version = "0.1.0"
authors = ["chip reed <chip@chip.sh>"]
edition = "2018"

[dependencies]
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-api = { path = "../../tauri-api", features = ["build"] }
thiserror = "1"
walkdir = "2"
zstd = "0.6"
