[package]
name = "tauri-sys"
version = "1.0.0"
authors = ["Boscop", "Lucas Fernandes Gon√ßalves Nogueira <lucas@quasar.dev>", "Daniel Thompson-Yvetot"]
license = "MIT"
repository = "https://github.com/tauri-apps/tauri"
description = "Rust native ffi bindings for tauri UI"
keywords = ["quasar", "web", "gui", "desktop", "webkit"]
categories = ["quasar", "gui", "web-programming", "api-bindings", "rendering", "visualization"]
build = "build.rs"
links = "tauri"
edition = "2018"

[lib]
name = "tauri_sys"
path = "lib.rs"

[dependencies]
bitflags = "1.0"

[build-dependencies]
cc = "1"
pkg-config = "0.3"
