workspace = {}

[package]
name = "tauri-cli"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas@tauri.studio>"]
edition = "2018"

[[bin]]
name = "cargo-tauri"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.0-beta.1", features = ["yaml"] }
anyhow = "1.0"
tauri-bundler = { path = "../tauri-bundler" }
colored = "2.0"
once_cell = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-inliner = "0.0.1"
kuchiki = "0.8"
html5ever = "0.25"
tiny_http = "0.8"
attohttpc = "0.15"
url = "2.1"
http = "0.2"
handlebars = "3.2"
notify = "4.0"
shared_child = "0.3"
toml_edit = "0.2"
convert_case = "0.4"
json-patch = "0.2"
