[package]
name = "proton-sys"
version = "1.0.0"
authors = ["Boscop", "Lucas Fernandes Gon√ßalves Nogueira <lucas@quasar.dev>", "Daniel Thompson-Yvetot <denjell@quasar.dev>"]
license = "MIT"
repository = "https://github.com/quasarframework/proton"
description = "Rust native ffi bindings for proton UI"
keywords = ["quasar", "web", "gui", "desktop", "webkit"]
categories = ["quasar", "gui", "web-programming", "api-bindings", "rendering", "visualization"]
build = "build.rs"
links = "proton"

[lib]
name = "proton_sys"
path = "lib.rs"

[dependencies]
bitflags = "1.0"

[build-dependencies]
cc = "1"
pkg-config = "0.3"
