name: build smoke tests

on: pull_request

jobs:
  via-prod:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        example: [gatsby/themed-site]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run: cargo install tauri-cli
    - name: install via yarn
      run: |
           cd ./examples/${{ matrix.example }}
           yarn
    - name: build example
      env:
        EXAMPLE_GATSBY_AIRTABLE_API_KEY: ${{ secrets.EXAMPLE_GATSBY_AIRTABLE_API_KEY }}
      run: |
           cd ./examples/${{ matrix.example }}
           yarn build
    - name: yarn tauri build
      run: |
           cd ./examples/${{ matrix.example }}
           yarn tauri:prod:build

  via-source:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        example:
          - name : GatsbyThemedSite
            folder: gatsby/themed-site
            executable: GatsbyThemedSiteApp

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
           sudo apt-get update
           sudo apt-get install -y webkit2gtk-4.0
    - name: build rust
      run: cargo build
      env:
        TAURI_DIST_DIR: ../../test/fixture/dist
        TAURI_CONFIG_DIR: ../test/fixture/
    - run: cargo install --path ./cli/tauri-cli --force
    - name: install cli deps via yarn
      run: |
           cd ./cli/tauri.js
           yarn
    - name: install via yarn
      run: |
           cd ./examples/${{ matrix.example.folder }}
           yarn
    - name: build example
      env:
        EXAMPLE_GATSBY_AIRTABLE_API_KEY: ${{ secrets.EXAMPLE_GATSBY_AIRTABLE_API_KEY }}
      run: |
           cd ./examples/${{ matrix.example.folder }}
           yarn build
    - name: yarn tauri build
      run: |
           cd ./examples/${{ matrix.example.folder }}
           yarn tauri:source:build
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: tauri built ${{ matrix.example.name }} on ${{ matrix.platform }}
        path: ./examples/${{ matrix.example.folder }}/src-tauri/target/release/${{ matrix.example.executable }}
