name: build smoke tests

on: pull_request

jobs:
  build-examples:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        example: [gatsby/themed-site]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: install via yarn
      run: |
           cd ./examples/${{ matrix.example }}
           yarn
    - name: build example
      run: |
           cd ./examples/${{ matrix.example }}
           yarn build
    - name: yarn tauri init
      run: |
           cd ./examples/${{ matrix.example }}
           yarn tauri:init
    - name: yarn tauri build
      run: |
           cd ./examples/${{ matrix.example }}
           yarn tauri:build
