name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest
    outputs:
      covector: ${{ steps.covector.outputs }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: covector status
        uses: jbolda/covector/packages/action@covector-v0
        id: covector
        with:
          command: 'status'

  dump-job-context:
    runs-on: ubuntu-latest
    needs: covector
    steps:
      - name: dump all output
        env:
          OUTPUT_CONTEXT: ${{ toJson(needs.covector) }}
        run: echo "$OUTPUT_CONTEXT"
      - name: dump covector output
        env:
          COVECTOR_CONTEXT: ${{ toJson(needs.covector.covector) }}
        run: echo "$COVECTOR_CONTEXT"
      - name: test successfulPublish
        if: ${{ needs.covector.covector.successfulPublish }} == 'true'
        run: echo this should be skipped
