# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: test create-tauri-app

on:
  workflow_dispatch:
    inputs:
      branch:
        default: "dev"
      test:
        default: "false"
  pull_request:
    paths:
      - "tooling/create-tauri-app/**"

env:
  RUST_BACKTRACE: 1

jobs:
  create-recipe-with-npm:
    name: npm@${{ matrix.manager }} and node@${{ matrix.node }} with ${{ matrix.recipe }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["14", "16"]
        manager: ["6", "7"] # TODO add yarn
        recipe: ["vanillajs", "reactjs", "reactts", "vite", "vuecli"]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
          npm-version: ${{ matrix.manager }}
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: yarn
        working-directory: tooling/create-tauri-app
      - run: yarn test
        working-directory: tooling/create-tauri-app
        env:
          TAURI_RECIPE: ${{ matrix.recipe }}
          TAURI_RUN_MANAGER: "npm"

  create-recipe-with-yarn:
    name: yarn and node@${{ matrix.node }} with ${{ matrix.recipe }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["14", "16"]
        recipe: ["vanillajs", "reactjs", "reactts", "vite", "vuecli"]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
          yarn-version: 1.22.5
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: yarn
        working-directory: tooling/create-tauri-app
      - run: yarn test
        working-directory: tooling/create-tauri-app
        env:
          TAURI_RECIPE: ${{ matrix.recipe }}
          TAURI_RUN_MANAGER: "yarn"
