# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: test create-tauri-app

on:
  workflow_dispatch:
    inputs:
      platform:
        default: "ubuntu"
  pull_request:
    paths:
      - "tooling/create-tauri-app/**"

env:
  RUST_BACKTRACE: 1

jobs:
  create-recipe-with-npm:
    name: "node@${{ matrix.node }} + npm@${{ matrix.manager }}: ${{ matrix.recipe }}"
    runs-on: ${{ github.event.inputs.platform || 'ubuntu' }}-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["14", "16"]
        manager: ["6", "7"]
        recipe: ["vanillajs", "cra", "vite", "ngcli"]
        exclude:
          - node: "16"
            manager: "6"

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
          npm-version: ${{ matrix.manager }}
          yarn-version: 1.22.5
      - name: install webkit2gtk
        if: (github.event.inputs.platform || 'ubuntu') == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev
      - run: yarn
        working-directory: tooling/cli.js
      - run: yarn build
        working-directory: tooling/cli.js
      - run: yarn
        working-directory: tooling/api
      - run: yarn build
        working-directory: tooling/api
      - run: yarn
        working-directory: tooling/create-tauri-app
      - run: yarn build
        working-directory: tooling/create-tauri-app
      - run: yarn test
        working-directory: tooling/create-tauri-app
        env:
          TAURI_RECIPE: ${{ matrix.recipe }}
          TAURI_RUN_MANAGER: "npm"

  create-recipe-with-yarn:
    name: "node@${{ matrix.node }} + yarn@1: ${{ matrix.recipe }}"
    runs-on: ${{ github.event.inputs.platform || 'ubuntu' }}-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["14", "16"]
        recipe: ["vanillajs", "cra", "vite", "ngcli"]

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
          yarn-version: 1.22.5
      - name: install webkit2gtk
        if: (github.event.inputs.platform || 'ubuntu') == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev
      - run: yarn
        working-directory: tooling/create-tauri-app
      - run: yarn build
        working-directory: tooling/create-tauri-app
      - run: yarn test
        working-directory: tooling/create-tauri-app
        env:
          TAURI_RECIPE: ${{ matrix.recipe }}
          TAURI_RUN_MANAGER: "yarn"
