# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: test android

on:
  pull_request:
    paths:
      - '.github/workflows/test-android.yml'
      - 'tooling/cli/templates/mobile/android/**'
      - 'tooling/cli/src/mobile/**'
      - '!tooling/cli/src/mobile/ios.rs'
      - '!tooling/cli/src/mobile/ios/**'
      - 'core/tauri-build/src/mobile.rs'
      - 'core/tauri/mobile/android/**'
      - 'core/tauri/mobile/android-codegen/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.1

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: |
            tooling/api/yarn.lock
            examples/api/yarn.lock

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          local-cache: true

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            tooling/cli
            examples/api/src-tauri

      - name: build CLI
        run: cargo build --manifest-path ./tooling/cli/Cargo.toml

      - name: build Tauri API
        working-directory: ./tooling/api
        run: yarn && yarn build

      - name: install API example dependencies
        working-directory: ./examples/api
        run: yarn

      - name: init Android Studio project
        working-directory: ./examples/api
        run: ../../tooling/cli/target/debug/cargo-tauri android init
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: build APK
        working-directory: ./examples/api
        run: ../../tooling/cli/target/debug/cargo-tauri android build
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
